version: '3.8'

services:
  web:
    build: server
    command: python main.py
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=db
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build: bot
    depends_on:
      - db
    command: python bot.py

volumes:
  db_data:
